#!/bin/python3

#Functions==============

def who_am_i(): 
	name = "Heath"
	age = 30
	print("My name is " + name + " and I am " + str(age) + " years old.")
	
who_am_i()

#adding parameters

def add_one_hundred(num):
		print(num+100)

add_one_hundred(100)


#multiple parameters

def add(x, y):
		print(x+y)
add(7, 7)

def multiply(x, y):
		return x * y
		
print(multiply(7, 7))


def square_root(x):
		print(x ** .5)
		
square_root(64)


def nl():
		print('\n')
		
nl()


#Boolean expression=================

print("Boolean expressions:")

bool1 = True
bool2 = 3*3 == 9
bool3 =  False
bool4 = 3 * 3 != 9

print(bool1, bool2, bool3, bool4)
print(type(bool1))


# Relational Boolean Orerators======

greater_than = 7 > 5
less_than = 5 < 7
greater_than_equal_to = 7 >= 7
less_than_equal_to = 7 <= 7

test_and = (7 > 5) and (5 < 7) # True
test_and2 = (7 > 5) and (5 > 7) #Fa;se
test_or = (7 > 5) or (5 > 7) #True
test_or2 = (7 > 5) or (5 > 7) #True

test_not = not True #False


#Conditional Statements=============
def drink(money):
		if money >= 2:
				return "You've got yourself a drink!"
		else: 
				return "No drink for you!"
print(drink(3))
print(drink(1))


#Lists==============================
	#Have Brackets []

movies = ["When Harry Met Sally", "The hangover", "The Perks of Being a Wallflower", "The Exorcist"]

print(movies[1])  # return the second item
print(movies[0])  # print the first item
print(movies[1:4])  #starting from 1 not included 4
print(movies[1: ])  # starting from 1 until end of the list
print(movies[ :1])

print(movies[-1]

	#len()

print(len(movies))
movies.append("Jaws")
print(movies) # will print new list with 'Jaws'

	#pop()
	
movies.pop() # pop() remove last added item
print(movies)

movies.pop(0)
print(movies)


# Tuple - DO NOT Change, ()

grades = ("a", "b", "c", "d", "f") # we cannot add or remove any item form this immutable list not changeble only following way to read only readble.... no pop() 

print(grades[1])

# Looping 

# For loops - start to finish of iterate===
vegetable = ["cucmber", "spanich", "cabbage"]
for x in vegetables:
		print(x)
		
# While loops - Execute as long as true====

i = 1

while i < 10:
		print(i)
		i += 1


# Importing Modules=========================

# sys whic is needs to import for python lib..

#!/bin/python3

import sys  #sys is system function  and parameters

print(sys.version)

sys.exit()


import sys  #sys is system function  and parameters

from datetime import datetime as dt # import with alias

print(dt.now())



my_name = "Dervis"
print(my_name[0])
print(my_name[-1])

sentence = "This is a sentence."
print(sentence[:4])


print(sentence.split())

sentence_split = sentence.split()
sentence_join = ' '.join(sentence_split)
print(sentence_join)

# Character Escaping He said, "give me all your money"
quote = "He said, \"give me all your money\"" # you can't use double quote in double quote without backslash
quote2 = "He said, 'give me all your money'" # also single quote work like this without problem
print(quote)
print(quote2)

too_much_space = "                      hello            "
print(too_much_space.strip())

print("a" in "Apple") # --- False

letter - "A"
word = "Apple"
print(letter.lower() in word.lower()) # Improved --- True


movie = "The hangover"
print("My favorite movie is {}.".format(movie))



#Dictionaries - key/Value pairs {} 
drinks = {'White Russian': 7, 'Old Fashion': 10, 'Lemon Drop': 8} # drink is key, price is value
print(drinks)

employees = {"Finance": ["Bob", "Tina"], "IT": ["Gene", "Lousie", "Teddy"], "HR":["Jimmy Jr.", "Mort"]}
print(employees)

employees['Legal'] = ["Mr. Frond"] # add new key : value pair
print(employees)

employees.update({"Sales": ["Andie", "Ollie"]}) # add new key:value pair
print(employees)

drinks['White Russian'] = 8
print(drinks)

print(drinks.get("White Russian"))


